name: project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.2
  firebase_auth: ^4.19.5
  firebase_auth_web: ^5.11.5
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    
    - assets/images/product1.png
    - assets/images/frank.png
    - assets/images/sehto.png
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Bold.ttf

    - family: SquadaOne
      fonts:
        - asset: assets/fonts/SquadaOne-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
